import { Contact } from '@/components/Contacts'
import { Experience } from '@/components/Experience'
import { Header } from '@/components/Header'
import { Profile } from '@/components/Profile'
import { Skill } from '@/components/Skill'
import { api } from '@/lib/axios'
import { IProfile } from '@/types/profile'
import { differenceInYears } from 'date-fns'
import { GetStaticProps } from 'next'
import Head from 'next/head'

interface IHomeProps {
  profile: IProfile
}

export default function Home({ profile }: IHomeProps) {
  return (
    <>
      <Head>
        <title>{profile.name} - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Profile profile={profile} />
      <Skill />
      <Experience />
      <Contact />
    </>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get('/users/anishigouri')

  const age = differenceInYears(new Date(), new Date(1988, 9, 18))

  const profile: IProfile = {
    avatarUrl: data.avatar_url,
    age,
    description: `Olá, tenho ${age} anos, sou formado em Ciência da Computação e sou
    desenvolvedor a aproximadamente 12 anos, fui fullstack durante 6 anos
    e atualmente sou frontend. Tenho mais conhecimento com a biblioteca React e o Framework Vue. `,
    name: data.name,
    career: 'frontend developer',
  }

  return {
    props: {
      profile,
    },
  }
}
